### ISSUE TITLE
Archetype Logs Exception When Viewing Fieldset with Property of Type Tags

### ISSUE THREAD

**Issue by Nicholas-Westby** [kgiszewski/Archetype#326]
I get this exception in my Umbraco log whenever I view an Archetype fieldset with a property of type "tags":

```
 2016-02-01 10:37:56,675 [P4972/D4/T36] ERROR Archetype.PropertyEditors.ArchetypePropertyEditor+ArchetypePropertyValueEditor - Type validation failed. The value type: 'JArray' does not match the DataType in PropertyType with alias: 'tags'
System.Exception: Type validation failed. The value type: 'JArray' does not match the DataType in PropertyType with alias: 'tags'
   at Umbraco.Core.Models.Property.set_Value(Object value)
   at Umbraco.Core.Models.Property..ctor(PropertyType propertyType, Object value)
   at Archetype.PropertyEditors.ArchetypePropertyEditor.ArchetypePropertyValueEditor.ConvertDbToEditor(Property property, PropertyType propertyType, IDataTypeService dataTypeService)
```

Here's what my fieldset looks like:

![fieldset](https://cloud.githubusercontent.com/assets/5933222/12727301/3f28734e-c8d1-11e5-9431-c3f6c6db0242.png)

Here's how my tags data type is configured:

![tags](https://cloud.githubusercontent.com/assets/5933222/12727315/538cd7d0-c8d1-11e5-8437-d99a48678c2c.png)

The only mentionable aspect about this configuration is that I'm using a storage type of "Json". This prevalue was added not too long ago based on a feature request I made. Long story short, the CSV format used by the tags data type wasn't playing nicely with tags that contained a comma, and this new option to store as JSON rather than CSV allowed more flexibility in the types of tags I could enter. Just mentioning that as it seems somewhat related to the error I'm seeing.

Umbraco 7.3.4. Archetype 1.12.2.

**Comment by kgiszewski** [comment]
I know we're not doing anything tag specific that would cause this. Is it possible you have an old Archetype holding a CSV format? So when something tries to deserialize it is looking for JSON instead?

**Comment by Nicholas-Westby** [comment]
@kgiszewski Nope, I just created this fieldset.

**Comment by kgiszewski** [comment]
Well crap :)

I'll have to look into this when I get a chance. About to leave on a vacation soon so it could be a few weeks.

**Comment by Nicholas-Westby** [comment]
No worries. I am just seeing entries in the error log. I haven't actually seen anything break yet.

**Comment by Nicholas-Westby** [comment]
I take that back. There does actually seem to be an error in the JavaScript console which may be related:

![tags-error](https://cloud.githubusercontent.com/assets/5933222/12728786/4df8a5ea-c8d8-11e5-8136-0adc09691183.png)

That appears when I view (in the back office) the page with the Archetype fieldset that contains the tags property.

**Comment by vmburd** [comment]
This issue may be related to the one I've just encountered with a slightly different error message:

```
ERROR Archetype.PropertyEditors.ArchetypePropertyEditor+ArchetypePropertyValueEditor - Type validation failed. The value type: 'JObject' does not match the DataType in PropertyType with alias: 'agendaStatus'
System.Exception: Type validation failed. The value type: 'JObject' does not match the DataType in PropertyType with alias: 'agendaStatus'
   at Umbraco.Core.Models.Property.set_Value(Object value)
   at Umbraco.Core.Models.Property..ctor(PropertyType propertyType, Object value)
   at Archetype.PropertyEditors.ArchetypePropertyEditor.ArchetypePropertyValueEditor.ConvertDbToString(Property property, PropertyType propertyType, IDataTypeService dataTypeService)
```

In my case, agendaStatus is a custom datatype w/property editor containing 8 true/false fields. I haven't received the Javascript error in the backend; this may be because none of my fields are marked as required.

The agendaStatus data is saved as JSON.  Full JSON of archetype is below:
```
{
	"fieldsets": [{
		"properties": [{
			"alias": "linkToBill",
			"value": "170415",
			"propertyEditorAlias": "Umbraco.MultiNodeTreePicker",
			"dataTypeId": 9725,
			"dataTypeGuid": "6ddb128c-608b-4522-89b3-13623163361f",
			"editorState": null,
			"hostContentType": null
		},
		{
			"alias": "vote",
			"value": "0",
			"propertyEditorAlias": "Umbraco.TrueFalse",
			"dataTypeId": -49,
			"dataTypeGuid": "92897bc6-a5f3-4ffe-ae27-f2e7e33dda49",
			"editorState": null,
			"hostContentType": null
		},
		{
			"alias": "number",
			"value": "13",
			"propertyEditorAlias": "Umbraco.Textbox",
			"dataTypeId": -88,
			"dataTypeGuid": "0cc0eba1-9960-42c9-bf9b-60e150b429ae",
			"editorState": null,
			"hostContentType": null
		},
		{
			"alias": "titleMT",
			"value": "Test",
			"propertyEditorAlias": "Umbraco.Textbox",
			"dataTypeId": -88,
			"dataTypeGuid": "0cc0eba1-9960-42c9-bf9b-60e150b429ae",
			"editorState": null,
			"hostContentType": null
		},
		{
			"alias": "title",
			"value": "",
			"propertyEditorAlias": "Umbraco.Textbox",
			"dataTypeId": -88,
			"dataTypeGuid": "0cc0eba1-9960-42c9-bf9b-60e150b429ae",
			"editorState": null,
			"hostContentType": null
		},
		{
			"alias": "agendaStatus",
			"value": {
				"reading1": true,
				"reading2": false,
				"reading2Cont": false,
				"committee": false,
				"committeeCont": false,
				"rCommittee": false,
				"reading3": false,
				"reading3Cont": false
			},
			"propertyEditorAlias": "cmsHoR.BillStatus",
			"dataTypeId": 171578,
			"dataTypeGuid": "569a4db4-2180-4f6d-894d-46d9271cb9bd",
			"editorState": null,
			"hostContentType": null
		},
		{
			"alias": "discussed",
			"value": "0",
			"propertyEditorAlias": "Umbraco.TrueFalse",
			"dataTypeId": -49,
			"dataTypeGuid": "92897bc6-a5f3-4ffe-ae27-f2e7e33dda49",
			"editorState": null,
			"hostContentType": null
		},
		{
			"alias": "statusAfterSitting",
			"value": {
				"reading1": false,
				"reading2": false,
				"reading2Cont": false,
				"committee": false,
				"committeeCont": false,
				"rCommittee": false,
				"reading3": false,
				"reading3Cont": false
			},
			"propertyEditorAlias": "cmsHoR.BillStatus",
			"dataTypeId": 171578,
			"dataTypeGuid": "569a4db4-2180-4f6d-894d-46d9271cb9bd",
			"editorState": null,
			"hostContentType": null
		},
		{
			"alias": "excludeFromOrdersOfTheDay",
			"value": "0",
			"propertyEditorAlias": "Umbraco.TrueFalse",
			"dataTypeId": -49,
			"dataTypeGuid": "92897bc6-a5f3-4ffe-ae27-f2e7e33dda49",
			"editorState": null,
			"hostContentType": null
		},
		{
			"alias": "linkToMps",
			"value": "",
			"propertyEditorAlias": "Umbraco.MultiNodeTreePicker",
			"dataTypeId": 5632,
			"dataTypeGuid": "821df1ea-4750-4c44-8936-e55f279ea07f",
			"editorState": null,
			"hostContentType": null
		},
		{
			"alias": "linkToSubstituteMps",
			"value": "",
			"propertyEditorAlias": "Umbraco.MultiNodeTreePicker",
			"dataTypeId": 5632,
			"dataTypeGuid": "821df1ea-4750-4c44-8936-e55f279ea07f",
			"editorState": null,
			"hostContentType": null
		}],
		"alias": "billStatus",
		"disabled": false,
		"id": "58b7a5e8-c918-4dc9-bed7-7772d259e0a3",
		"collapse": false,
		"isValid": true
	}]
}
```


I'm using Umbraco 7.4.1, Archetype 1,12,2

**Comment by kgiszewski** [comment]
@vmburd, thanks for posting. Can you also share your `package.manifest`?

**Comment by vmburd** [comment]
Sure.  Here's the manifest
```

{
	propertyEditors: [
		{
			alias: "cmsHoR.BillStatus",
			name: "Bill Status",
			editor: {
				view: "~/App_Plugins/HoRBillStatus/HoRBillStatus.html"
			}
		}
	]
	,
	javascript: [
		'~/App_Plugins/HoRBillStatus/HoRBillStatus.controller.js'
	]
}
```
This property editor doesn't need any configuration as it's quite straightforward.

For completeness sake, here's the HTML
```
<div ng-controller="cmsHoR.BillStatus" id="cmsHoR_BillStatus">
    <div class="control-group umb-control-group">
            <div class="umb-property-editor">
                <label for="reading1">
                    <input type="checkbox" id="reading1"
                           ng-model="model.value.reading1" />1st Reading<small>Is this the 1st reading of this bill?</small>
                </label>
            </div>

        <div>
            <div class="umb-property-editor pull-left">
                <label for="reading2">
                    <input type="checkbox" id="reading2"
                           ng-change="toggleCont('reading2')"
                           ng-model="model.value.reading2" />2nd Reading<small>Is this the 2nd reading of this bill?</small>
                </label>
            </div>

            <div class="umb-property-editor pull-right">
                <label for="reading2Cont">
                    <input type="checkbox" id="reading2Cont"
                           ng-model="model.value.reading2Cont" 
                           ng-disabled="!model.value.reading2"/>2nd Reading Continued<small>Is this a continuation of the 2nd reading of this bill?</small>
                </label>
            </div>
        </div>
        <div style="clear: both"></div>
        <div>
            <div class="umb-property-editor pull-left">
                <label for="committee">
                    <input type="checkbox" id="committee" 
                           ng-change="toggleCont('committee')"
                           ng-model="model.value.committee" />Committee<small>Has the bill reached committee stage?</small>
                </label>
            </div>

            <div class="umb-property-editor pull-right">
                <label for="committeeCont">
                    <input type="checkbox" id="committeeCont" 
                           ng-model="model.value.committeeCont" 
                           ng-disabled="!model.value.committee"/>Committee Continued<small>Is this a continuation of the Committee stage of this bill?</small>
                </label>
            </div>
        </div>
        <div style="clear: both"></div>

		<div class="umb-property-editor">
            <label for="rCommittee">
                <input type="checkbox" id="rCommittee" 
                       ng-model="model.value.rCommittee"/>Referred back to Committee<small>Has the bill been referred back to the committee?</small>
            </label>
        </div>

        <div>
            <div class="umb-property-editor pull-left">
                <label for="reading3">
                    <input type="checkbox" id="reading3"
                           ng-change="toggleCont('reading3')"
                           ng-model="model.value.reading3" />3rd Reading<small>Is this the 3rd reading of this bill?</small>
                </label>
            </div>
            <div class="umb-property-editor pull-right">
                <label for="reading3Cont">
                    <input type="checkbox" id="reading3Cont"
                           ng-model="model.value.reading3Cont" 
                           ng-disabled="!model.value.reading3" />3rd Reading Continued<small>Is this a continuation of the 3rd reading of this bill?</small>
                </label>
            </div>
        </div>
    </div>
</div>

```

And finally, here's the controller (very rough and ready)

```
angular.module("umbraco").controller("cmsHoR.BillStatus", function ($scope) {
    if ($scope.model.value === null || $scope.model.value === "")
    {
       //set initial state of all check boxes to false
        $scope.model.value = {
            reading1: false,
            reading2: false,
            reading2Cont: false,
            committee: false,
            committeeCont: false,
            rCommittee: false,
            reading3: false,
            reading3Cont: false
        }
    }

    $scope.toggleCont = function (changed)
    {
        //if we switch off a field we have to remove check for corresponding Cont. field
        switch(changed)
        {
            case "reading2":
                if (!$scope.model.value.reading2) $scope.model.value.reading2Cont = false;
                break;
            case "committee":
                if (!$scope.model.value.committee) $scope.model.value.committeeCont = false;
                break;
            case "reading3":
                if (!$scope.model.value.reading3) $scope.model.value.reading3Cont = false;
                break;
            default:
                break;
        }
    }
});
```

**Comment by kgiszewski** [comment]
In your manifest, can you add a property like the one below?

https://github.com/imulus/uWestFest/blob/master/urlpicker/config/package.manifest#L7

I'm wondering if it's saving it as text instead of JSON. It may explain @Nicholas-Westby's issue to since he changed the `tags` to JSON and started getting the error.

To test, make sure you clear all caches and update `compilation` tag in the `web.config` to `debug="true"`

**Comment by vmburd** [comment]
Made the change, still same error in log file.  Web site is already in debug mode

Package.manifest is now:

```
{
	"propertyEditors": [
		{
			"alias": "cmsHoR.BillStatus",
			"name": "Bill Status",
			"editor": {
		              "valueType": "JSON",
		              "view"": "~/App_Plugins/HoRBillStatus/views/HoRBillStatus.html"
			}
		}
	]
	,
	"javascript": [
		'~/App_Plugins/HoRBillStatus/HoRBillStatus.controller.js'
	]
}
```

However, in frontend I now get this error:

Received an error from the server

An error occured
```

Mapping types: DataTypeDefinition -> IEnumerable`1 Umbraco.Core.Models.DataTypeDefinition -> System.Collections.Generic.IEnumerable`1[[Umbraco.Web.Models.ContentEditing.PreValueFieldDisplay, umbraco, Version=1.0.5891.23243, Culture=neutral, PublicKeyToken=null]] Destination path: DataTypeDisplay.PreValues.PreValues Source value: Umbraco.Core.Models.DataTypeDefinition
Exception Details
AutoMapper.AutoMapperMappingException: Mapping types: DataTypeDefinition -> IEnumerable`1 Umbraco.Core.Models.DataTypeDefinition -> System.Collections.Generic.IEnumerable`1[[Umbraco.Web.Models.ContentEditing.PreValueFieldDisplay, umbraco, Version=1.0.5891.23243, Culture=neutral, PublicKeyToken=null]] Destination path: DataTypeDisplay.PreValues.PreValues Source value: Umbraco.Core.Models.DataTypeDefinition
[defaultdialogs_stacktrace]

at Archetype.Api.ArchetypeDataTypeController.GetByGuid(Guid guid)

   at lambda_method(Closure , Object , Object[] )

   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)

   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)

   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()


```

**Comment by vmburd** [comment]
Ignore the frontend error bit - I had an extra quote after view in my package.manifest file. Original issue still stands though.

**Comment by kgiszewski** [comment]
ok thanks for trying. will have to find some time to properly debug this.

**Comment by vmburd** [comment]
On a side note, if I have developer options turned on and I save the document, the text for the archetype model is replaced by [Object] [object]. Refreshing the page brings the correct display back.

**Comment by kjac** [comment]
I have a fix for this, but for JSON tags only.

Does anyone have a razor snippet that shows how you'd want to use tags in a fieldset?

**Comment by Nicholas-Westby** [comment]
@kjac I use Ditto to map content, but here's a function I use to convert JSON tags to a list of strings:

        /// <summary>
        /// Gets the list of tags.
        /// </summary>
        /// <param name="tagsJson">The tags to parse.</param>
        /// <returns>
        /// The tags.
        /// </returns>
        public static List<string> GetTags(dynamic tagsJson)
        {
            var tags = new List<string>();
            if (tagsJson == null)
            {
                return tags;
            }
            if (tagsJson is string)
            {
                var deserializedTags = JsonConvert.DeserializeObject(tagsJson as string) as dynamic;
                foreach (var item in deserializedTags)
                {
                    tags.Add((item.Value) as string);
                }
            }
            else
            {
                foreach (var item in tagsJson)
                {
                    tags.Add((item.Value) as string);
                }
            }
            return tags;
        }

**Comment by kjac** [comment]
Thanks @Nicholas-Westby, that helped verifying the bug fix.

**Comment by vmburd** [comment]
Has there been any progress on this for fieldsets rendered as JObject ?  I'm getting close to releasing my website and this is the last major stumbling block.  As it stands, every publish/re-index operation fills up the error log with ConvertDbToString Archetype error messages 

Thanks

**Comment by kgiszewski** [comment]
@vmburd I submitted a PR to the core team regarding this issue but I have a feeling it won't get accepted: http://issues.umbraco.org/issue/U4-8345

For whatever reason the Tags data type is returning `JObject` or `JArray`.

I'm going to look into forcing Archetype to only send strings if the above types are detected. That way we won't have to go through with a PR to the core.

**Comment by kgiszewski** [comment]
@vmburd, the update on this is I have a PR for Archetype that will likely fix this: https://github.com/imulus/Archetype/pull/359

**Comment by vmburd** [comment]
Thanks for the outstanding work on this package @kgiszewski. I'll keep an eye out for that PR.

**Comment by kgiszewski** [comment]
Closing due to age of ticket with no activity, please re-open if still relevant.
